/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Apoyo.Validacion;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.WindowConstants;

/**
 *
 * @author Harby
 */
public class VCrearEditarOrden extends javax.swing.JPanel {

    private JFrame frame = new JFrame("Agregar Editar Orden");
    private JDialog dialog;
    private PCrearEditarOrden presentador;
    private Validacion validar = new Validacion();
    
    public VCrearEditarOrden() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        paneltitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelModificarOrden = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        paneltxt = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboxCentro = new javax.swing.JComboBox<>();
        cboxProveedor = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cboxTipoPago = new javax.swing.JComboBox<>();
        cboxFormaPago = new javax.swing.JComboBox<>();
        panelCrearOrden = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btncancelarm = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setBackground(new java.awt.Color(204, 255, 204));

        paneltitle.setBackground(new java.awt.Color(0, 204, 0));

        jLabel1.setBackground(new java.awt.Color(153, 204, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AGREGAR ORDEN DE COMPRA");

        javax.swing.GroupLayout paneltitleLayout = new javax.swing.GroupLayout(paneltitle);
        paneltitle.setLayout(paneltitleLayout);
        paneltitleLayout.setHorizontalGroup(
            paneltitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );
        paneltitleLayout.setVerticalGroup(
            paneltitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneltitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelModificarOrden.setBackground(new java.awt.Color(204, 255, 204));

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modify.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btncancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/undo.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelModificarOrdenLayout = new javax.swing.GroupLayout(panelModificarOrden);
        panelModificarOrden.setLayout(panelModificarOrdenLayout);
        panelModificarOrdenLayout.setHorizontalGroup(
            panelModificarOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarOrdenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        panelModificarOrdenLayout.setVerticalGroup(
            panelModificarOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModificarOrdenLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panelModificarOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        paneltxt.setBackground(new java.awt.Color(204, 255, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("tipoPago:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("FormaPago:");

        cboxCentro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboxProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("CentroCosto:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Proveedor:");

        cboxTipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboxFormaPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout paneltxtLayout = new javax.swing.GroupLayout(paneltxt);
        paneltxt.setLayout(paneltxtLayout);
        paneltxtLayout.setHorizontalGroup(
            paneltxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltxtLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(paneltxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneltxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cboxProveedor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboxCentro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboxTipoPago, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboxFormaPago, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paneltxtLayout.setVerticalGroup(
            paneltxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltxtLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(paneltxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboxTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneltxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cboxFormaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(paneltxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(paneltxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelCrearOrden.setBackground(new java.awt.Color(204, 255, 204));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/check.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btncancelarm.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btncancelarm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.png"))); // NOI18N
        btncancelarm.setText("Cancelar");
        btncancelarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCrearOrdenLayout = new javax.swing.GroupLayout(panelCrearOrden);
        panelCrearOrden.setLayout(panelCrearOrdenLayout);
        panelCrearOrdenLayout.setHorizontalGroup(
            panelCrearOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearOrdenLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnGuardar)
                .addGap(60, 60, 60)
                .addComponent(btncancelarm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCrearOrdenLayout.setVerticalGroup(
            panelCrearOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearOrdenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCrearOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncancelarm, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneltitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelModificarOrden, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(paneltxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelCrearOrden, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(paneltitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelModificarOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCrearOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        this.cerrar();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (isValidatedForm()) {
            presentador.modificarOrden();
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (isValidatedForm()) {
            presentador.guardarOrden();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btncancelarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarmActionPerformed
        this.cerrar();
    }//GEN-LAST:event_btncancelarmActionPerformed
    public void setPresentador(PCrearEditarOrden p) {
        presentador = p;
    }

    public void iniciar(){       
        dialog = new JDialog(frame,true);
        dialog.setContentPane(this);
        dialog.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        dialog.pack();
        dialog.setSize(650, 400);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);//poner despues del null para centrar
    }
    
    public void cerrar(){
        frame.dispose();
    }
    
    public void deshabilitarBotones(){
        this.panelModificarOrden.setVisible(false);
        this.panelCrearOrden.setVisible(false);
    }
        
    public void habilitarBtnsEmpleadoAgregar(){
        this.panelCrearOrden.setVisible(true);
    }
    public void habilitarBtnsEmpleadoModificar(){
        this.panelModificarOrden.setVisible(true);
    }
    
    public String getTipoPagoSeleccionada(){
        return this.cboxTipoPago.getSelectedItem().toString();
    }
    
    public String getFormaPagoSeleccionada(){
        return this.cboxFormaPago.getSelectedItem().toString();
    }
    
    public String getProveedorSeleccionada(){
        String idTipo = this.cboxProveedor.getSelectedItem().toString();
        idTipo = idTipo.split("-")[0];
        return idTipo;
    }
    
    public String getCentroSeleccionada(){
        String idTipo = this.cboxCentro.getSelectedItem().toString();
        idTipo = idTipo.split("-")[0];
        return idTipo;
    }
    
    public void setTipoPago(String pago){
        for (int i = 0; i < cboxTipoPago.getItemCount(); i++) {
            if (cboxTipoPago.getItemAt(i).equals(pago)) {
                cboxTipoPago.setSelectedIndex(i);
            }
        }    
    }
    
    public void setFormaPago(String forma){
        for (int i = 0; i < cboxFormaPago.getItemCount(); i++) {
            if (cboxFormaPago.getItemAt(i).equals(forma)) {
                cboxFormaPago.setSelectedIndex(i);
            }
        }  
    }
    
    public void setProveedor(String id, String proveedor){
        for (int i = 0; i < cboxProveedor.getItemCount(); i++) {
            if (cboxProveedor.getItemAt(i).equals(id+"-"+proveedor)) {
                cboxProveedor.setSelectedIndex(i);
            }
        } 
    }
    
    public void setCentro(String id, String centro){
        for (int i = 0; i < cboxCentro.getItemCount(); i++) {
            if (cboxCentro.getItemAt(i).equals(id+"-"+centro)) {
                cboxCentro.setSelectedIndex(i);
            }
        }
    }

    public void mostrarListaTiposPago(String[] tipos){
        this.cboxTipoPago.setModel( new DefaultComboBoxModel<>( tipos ) );
    }
    
    public void mostrarListaFormasPago(String[] tipos){
        this.cboxFormaPago.setModel( new DefaultComboBoxModel<>( tipos ) );
    }
    
    public void mostrarListaProveedores(String[] tipos){
        this.cboxProveedor.setModel( new DefaultComboBoxModel<>( tipos ) );
    }
    
    public void mostrarListaCentros(String[] tipos){
        this.cboxCentro.setModel( new DefaultComboBoxModel<>( tipos ) );
    }

    private boolean isValidatedForm(){
       
        if (cboxTipoPago.getSelectedItem()==null) {
            return false;
        }
        
        if (cboxFormaPago.getSelectedItem()==null) {
            return false;
        }
        
        if (cboxProveedor.getSelectedItem()==null) {
            return false;
        }
        
        if (cboxCentro.getSelectedItem()==null) {
            return false;
        }
        
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btncancelarm;
    private javax.swing.JComboBox<String> cboxCentro;
    private javax.swing.JComboBox<String> cboxFormaPago;
    private javax.swing.JComboBox<String> cboxProveedor;
    private javax.swing.JComboBox<String> cboxTipoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel panelCrearOrden;
    private javax.swing.JPanel panelModificarOrden;
    private javax.swing.JPanel paneltitle;
    private javax.swing.JPanel paneltxt;
    // End of variables declaration//GEN-END:variables
}
